// Code generated by aah CLI, DO NOT EDIT
//
// aah framework v0.12.5 - https://aahframework.org
// FILE: aah.go
// DESC: aah application entry point

package main

import (
	"bytes"
	"os"

	_ "aah-recycleview-backend/app/generated"
	"aahframe.work"
	"aahframe.work/aruntime"
)

func main() {
	app := aah.App()
	defer func() {
		if r := recover(); r != nil {
			st := aruntime.NewStacktrace(r, app.Config())
			buf := new(bytes.Buffer)
			st.Print(buf)
			app.Log().Error(buf.String())
		}
	}()

	if err := app.Run(os.Args); err != nil {
		app.Log().Error(err)
	}
}
